# @package _global_
defaults:
  - data: curr
  - loop: curr
  - optim: curr
  - model: repl

load: null
mode: resume
device: 6
cuda: True
verbose: False
mlb_debug: True

plot:
  file: multiplot
  title: null