# @package _global_
defaults:
  - data: deepcoder
  - loader: curr
  - loop: curr
  - optim: curr
  - model: mbas
  - solver: astar # not used by model=rb

job_name: anon_job # used to be called `prefix`
run_name: anon_run # used to be called `name`
full_name: null # this will be set by matt.py to be {job_name}.{run_name}
load: null
mode: train
device: cpu
seed: 100 # null means random
print: False # just print the cfg and exit


dirty: False # set to True to skip errors due to dirty repo
is_dirty: null # set by matt.py. This tells whether the repo was actually dirty when launching

argv: null # this will get set by matt.py
commit: null # this will get set by matt.py
start_time: null # this will get set by matt.py
start_time_filename: null # this will get set by matt.py. It's a filename-safe version of start_time
job_id: null # not used internally for anything, just by the `job` manager.
job_info: null # optionally set by job.py to {time_str}.{self.job_name}.{run_name}

printif:
  fake: False # print_if(s,'fake') will only fire if this is True


notify_crash: null # null | email | text
notify_done: null  # null | email | text

debug:
  verbose: False
  mlb_debug: True
  channel: False # check gradients for channel separation (only between sketches not between examples)
  zero_output_feats: False # replace outputFeatures(task) with all zeros so _compare(rep,all_zeros) is run
  zero_input_feats: False # replace inputFeatures(task) with all zeros. This means holes are no longer a function of the input features.
  zero_concrete_eval: False # Take the result of encodeValue(rep) and turn it to all zeros
  zero_sk: False # Take the result of rep(sk) and turn it to all zeros so _compare(all_zeros,outputFeatures) is run
  validate_cache: False # double check that the cache is identical to the non-cache verison. Also applies to PTask.input_feats()
  pnode_concrete_check: True # cheap check to make sure both concrete-mode propagate() is working (equivalent to actual outputs) and execute_single() as well
  no_cache: False # disables caching altogether
plot: # for mode=plot
  file: null # defaults to time string
  title: null # defaults to time string
  legend: null # a string like "['Blended Semantics (ours)', 'Neural Semantics', 'RNN']"
  cropped: True
  font_size: 14
  linewidth: 4
  filetype: eps # only used if no `plot.file` is provided (otherwise we just use the extension on `plot.file`)
  x_max: null # manually set the x axis to a certain maximum

testgen: # for mode=test
  from_fn: null # deepcoder | josh | lucas
  to_file: null

test:
  from_file: null
  out: null # output file. defaults to job_info if thats set (job.py sets it to {time_str}.{self.job_name}.{run_name}), else to {sing.cfg.time_start_filename}.{sing.cfg.job_name}.{sing.cfg.run_name}
  timeout: 30
  max_tasks: null
  validator_vhead: True
  scaffold: False
  josh:
    wave: 3 # 1 | 2 | 3 | 3.1 | final
  lucas:
    version: 1 # 1 | 2 | 3 | old | bootstrap

hydra:
  run:
    dir: ./${mode}/${now:%Y-%m-%d}/${now:%H-%M-%S}.${job_name}.${run_name}