
# @package _group_
type: mbas
optim:
  lr: .001
ordering: right
tiebreaking: random
H: 64
max_var: 10
vhead: check_invalid # repl | rnn | check_invalid | uniform
phead: repl # repl | rnn | uniform
multidir: False
apply_mode: apply_nn # apply_nn | nmns
abstraction_fn: # AbstractionFn class
  modular: True
  digitwise: True
  bidir_ctx: True
  bidir_int: True 
pnode: # anything to do with pnodes, neural execution, blended execution, etc
  ctxful_lambdas: False
  encode_index_as: constant # inputs | constant
  allow_concrete_eval: True
apply:
  type: rnn # transformer | rnn
  bind: cat # cat | sum
  readout: first # first | sum
  gru_layers: 1



